<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.applitools.imagetester</groupId>
	<artifactId>ImageTester</artifactId>
	<version>3.10.1</version>
	<packaging>jar</packaging>
	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>

	<repositories>
		<repository>
			<id>central</id>
			<url>https://repo1.maven.org/maven2</url>
		</repository>

		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>com.applitools</groupId>
			<artifactId>eyes-universal-core-win</artifactId>
			<version>5.77.10</version>
		</dependency>
		<dependency>
			<groupId>com.applitools</groupId>
			<artifactId>eyes-universal-core-mac</artifactId>
			<version>5.77.10</version>
		</dependency>
		<dependency>
			<groupId>com.applitools</groupId>
			<artifactId>eyes-universal-core-mac-arm</artifactId>
			<version>5.77.10</version>
		</dependency>
		<dependency>
			<groupId>com.applitools</groupId>
			<artifactId>eyes-universal-core-linux</artifactId>
			<version>5.77.10</version>
		</dependency>
		<dependency>
			<groupId>com.applitools</groupId>
			<artifactId>eyes-universal-core-alpine</artifactId>
			<version>5.77.10</version>
		</dependency>
		<dependency>
			<groupId>com.applitools</groupId>
			<artifactId>eyes-universal-core-arm</artifactId>
			<version>5.77.10</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>4.11.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.applitools.eyesutilities</groupId>
			<artifactId>EyesUtilities</artifactId>
			<version>1.6.6</version>
		</dependency>
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
			<version>2.0.29</version>
		</dependency>
		<dependency>
			<groupId>com.applitools</groupId>
			<artifactId>eyes-images-java5</artifactId>
			<version>5.81.10</version>
		</dependency>
		<dependency>
			<groupId>commons-cli</groupId>
			<artifactId>commons-cli</artifactId>
			<version>1.6.0</version>
		</dependency>
		<dependency>
			<groupId>com.twelvemonkeys.imageio</groupId>
			<artifactId>imageio-jpeg</artifactId>
			<version>3.12.0</version>
		</dependency>
		<dependency>
			<groupId>com.twelvemonkeys.imageio</groupId>
			<artifactId>imageio-tiff</artifactId>
			<version>3.12.0</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.11.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.13.4</version>
		</dependency>
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>jbig2-imageio</artifactId>
			<version>3.0.4</version>
		</dependency>
		<dependency>
			<groupId>com.opencsv</groupId>
			<artifactId>opencsv</artifactId>
			<version>5.8</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-csv</artifactId>
			<version>2.13.4</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.32</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.applitools</groupId>
			<artifactId>eyes-sdk-core-java5</artifactId>
			<version>5.86.11</version>
		</dependency>
		<dependency>
			<groupId>org.commonmark</groupId>
			<artifactId>commonmark</artifactId>
			<version>0.21.0</version>
		</dependency>
		<dependency>
			<groupId>com.openhtmltopdf</groupId>
			<artifactId>openhtmltopdf-pdfbox</artifactId>
			<version>1.0.10</version>
		</dependency>
		<dependency>
			<groupId>net.java.dev.jna</groupId>
			<artifactId>jna-platform</artifactId>
			<version>5.18.1</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M4</version>
				<configuration>
					<excludes>
						<exclude>Tests/**</exclude>
						<exclude>infra/TestBase.java</exclude>
					</excludes>
				</configuration>
			</plugin>

			<plugin>
				<!-- Use lifecycle package to generate uber jar -->
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.4.1</version>
				<configuration>
					<transformers>
						<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
							<MainClass>com.applitools.imagetester.ImageTester</MainClass>
						</transformer>
					</transformers>
				</configuration>
				<executions>
					<execution>
						<id>shade-universal</id>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<outputFile>${project.basedir}/jars/${project.artifactId}_${project.version}.jar</outputFile>
							<shadedArtifactAttached>true</shadedArtifactAttached>
							<shadedClassifierName>universal</shadedClassifierName>
						</configuration>
					</execution>
					<execution>
						<id>shade-windows</id>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<outputFile>${project.basedir}/jars/${project.artifactId}_${project.version}_Windows.jar</outputFile>
							<shadedArtifactAttached>true</shadedArtifactAttached>
							<shadedClassifierName>windows</shadedClassifierName>
							<artifactSet>
								<excludes>
									<exclude>com.applitools:eyes-universal-core-mac</exclude>
									<exclude>com.applitools:eyes-universal-core-mac-arm</exclude>
									<exclude>com.applitools:eyes-universal-core-linux</exclude>
									<exclude>com.applitools:eyes-universal-core-alpine</exclude>
									<exclude>com.applitools:eyes-universal-core-arm</exclude>
								</excludes>
							</artifactSet>
						</configuration>
					</execution>
					<execution>
						<id>shade-mac</id>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<outputFile>${project.basedir}/jars/${project.artifactId}_${project.version}_Mac.jar</outputFile>
							<shadedArtifactAttached>true</shadedArtifactAttached>
							<shadedClassifierName>mac</shadedClassifierName>
							<artifactSet>
								<excludes>
									<exclude>com.applitools:eyes-universal-core-win</exclude>
									<exclude>com.applitools:eyes-universal-core-mac-arm</exclude>
									<exclude>com.applitools:eyes-universal-core-linux</exclude>
									<exclude>com.applitools:eyes-universal-core-alpine</exclude>
									<exclude>com.applitools:eyes-universal-core-arm</exclude>
								</excludes>
							</artifactSet>
						</configuration>
					</execution>
					<execution>
						<id>shade-mac-arm</id>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<outputFile>${project.basedir}/jars/${project.artifactId}_${project.version}_MacArm.jar</outputFile>
							<shadedArtifactAttached>true</shadedArtifactAttached>
							<shadedClassifierName>mac-arm</shadedClassifierName>
							<artifactSet>
								<excludes>
									<exclude>com.applitools:eyes-universal-core-win</exclude>
									<exclude>com.applitools:eyes-universal-core-mac</exclude>
									<exclude>com.applitools:eyes-universal-core-linux</exclude>
									<exclude>com.applitools:eyes-universal-core-alpine</exclude>
									<exclude>com.applitools:eyes-universal-core-arm</exclude>
								</excludes>
							</artifactSet>
						</configuration>
					</execution>
					<execution>
						<id>shade-linux</id>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<outputFile>${project.basedir}/jars/${project.artifactId}_${project.version}_Linux.jar</outputFile>
							<shadedArtifactAttached>true</shadedArtifactAttached>
							<shadedClassifierName>linux</shadedClassifierName>
							<artifactSet>
								<excludes>
									<exclude>com.applitools:eyes-universal-core-win</exclude>
									<exclude>com.applitools:eyes-universal-core-mac</exclude>
									<exclude>com.applitools:eyes-universal-core-mac-arm</exclude>
									<exclude>com.applitools:eyes-universal-core-alpine</exclude>
									<exclude>com.applitools:eyes-universal-core-arm</exclude>
								</excludes>
							</artifactSet>
						</configuration>
					</execution>
					<execution>
						<id>shade-alpine</id>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<outputFile>${project.basedir}/jars/${project.artifactId}_${project.version}_Alpine.jar</outputFile>
							<shadedArtifactAttached>true</shadedArtifactAttached>
							<shadedClassifierName>alpine</shadedClassifierName>
							<artifactSet>
								<excludes>
									<exclude>com.applitools:eyes-universal-core-win</exclude>
									<exclude>com.applitools:eyes-universal-core-mac</exclude>
									<exclude>com.applitools:eyes-universal-core-mac-arm</exclude>
									<exclude>com.applitools:eyes-universal-core-linux</exclude>
									<exclude>com.applitools:eyes-universal-core-arm</exclude>
								</excludes>
							</artifactSet>
						</configuration>
					</execution>
					<execution>
						<id>shade-arm</id>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<outputFile>${project.basedir}/jars/${project.artifactId}_${project.version}_Arm.jar</outputFile>
							<shadedArtifactAttached>true</shadedArtifactAttached>
							<shadedClassifierName>arm</shadedClassifierName>
							<artifactSet>
								<excludes>
									<exclude>com.applitools:eyes-universal-core-win</exclude>
									<exclude>com.applitools:eyes-universal-core-mac</exclude>
									<exclude>com.applitools:eyes-universal-core-mac-arm</exclude>
									<exclude>com.applitools:eyes-universal-core-linux</exclude>
									<exclude>com.applitools:eyes-universal-core-alpine</exclude>
								</excludes>
							</artifactSet>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<!-- This plugin required to control version addition to the manifest so it will be consumable on runtime -->
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.2.2</version>
				<configuration>
					<archive>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
							<addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
						</manifest>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.10.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>eyes-tests</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<configuration>
							<excludes combine.self="override" />
							<includes>
								<include>Tests/**</include>
							</includes>
							<parallel>methods</parallel>
							<threadCount>4</threadCount>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>multi-format-tests</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<configuration>
							<excludes combine.self="override" />
							<includes>
								<include>Tests/MultiFormatIntegrationTest.java</include>
							</includes>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
